spring:
  application:
    name: api-demo
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: true
#  data:
#    jpa:
#      repositories:
#        bootstrap-mode: default
logging:
  level:
    org.springframework.web: debug

